version: '3.7'
services: 
  backend:
    build: .
    image: backend:v1
    volumes: 
      - .:/code
    command: python run.py
    ports: 
      - 8080:8080
      - 8081:8080
    depends_on: 
      - mongo
    restart: on-failure
    environment: 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  
  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      - mongo